### PR TITLE
[#518] Build ghcide with GHC 8.10.1

### LINKED ISSUE #518: Build with GHC 8.10
I'm trying to build `ghcide` using recently released GHC 8.10. After updating dependencies correspondingly, I see the following error message:

```
src/Development/IDE/GHC/HieAst.hs:30:1: error:
    Could not find module ‘HsSyn’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
30 | import HsSyn
   | ^^^^^^^^^^^^

src/Development/IDE/GHC/HieAst.hs:37:37: error:
    Module ‘Type’ does not export ‘mkFunTys’
   |
37 | import Type                       ( mkFunTys, Type )
   |                                     ^^^^^^^^
```

I can see that at least the `HsSyn` module is not present in `ghc-lib-parser-8.10.1.20200324`.

cc @pepeiborra

### PR DESCRIPTION
**Pull request by chshersh**
Resolves #518

I was able to implement a small patch that allows `ghcide` to build with GHC 8.10. A couple of tests are failing, though. Any feedback is appreciated!

### CODE REVIEW

File: src/Development/IDE/Core/Rules.hs [hunk 1]
```diff
@@ -504,7 +506,11 @@ getHiFileRule = defineEarlyCutoff $ \GetHiFile f -> do
               case r of
                 Right iface -> do
                   let result = HiFileResult ms iface
+#if MIN_GHC_API_VERSION(8,10,0)
```
Comment (mpickering) [inline src/Development/IDE/Core/Rules.hs:509]: Please keep all CPP in the `Compat` module.

File: ghcide.cabal [hunk 2]
```diff
@@ -144,7 +144,7 @@ library
         Development.IDE.Plugin.CodeAction.RuleTypes
         Development.IDE.Plugin.Completions.Logic
         Development.IDE.Plugin.Completions.Types
-    if impl(ghc > 8.7) || flag(ghc-lib)
+    if (impl(ghc > 8.7) && impl(ghc < 8.10)) || flag(ghc-lib)
```
Comment (mpickering) [inline ghcide.cabal:147]: If this is correct, then why do we need the file in tree for 8.8 as well?

Comment (chshersh) [reply ghcide.cabal:147]: This file contains the implementation of the `mkHieFile` function. This function is present in GHC 8.10. And the implementation for GHC-8.8 is based on HIE files from GHC, where the implementation of this function for GHC 8.6 is based on `ghcide` own reimplementation of HIE files. So there are 3 cases for this function.

File: src/Development/IDE/Core/Rules.hs (hunk 1 above)
Comment (chshersh) [reply src/Development/IDE/Core/Rules.hs]: Done

File: src/Development/IDE/GHC/HieAst.hs [hunk 3]
```diff
@@ -94,12 +94,12 @@ type HieM = ReaderT HieState Hsc
...
           -> TcGblEnv
           -> RenamedSource
-          -> BS.ByteString
           -> Hsc HieFile
-mkHieFile ms ts rs src = do
+mkHieFile ms ts rs = do
   let tc_binds = tcg_binds ts
   (asts', arr) <- getCompressedAsts tc_binds rs
   let Just src_file = ml_hs_file $ ms_location ms
+  src <- liftIO $ BS.readFile src_file
```
Comment (chshersh) [inline src/Development/IDE/GHC/HieAst.hs:102]: It is how the `mkHieFile` function is implemented in GHC 8.10. This function is called only once in the whole codebase and empty string `""` is passed as an argument to it instead of `src`. Maybe this was done for some performance/memory reasons, but I made the implementation consistent with GHC 8.10 to have fewer surprises.

File: ghcide.cabal (hunk 2 above)
Comment (pepeiborra) [reply ghcide.cabal:147]: The version of `mkHieFile` in GHC 8.8 was unsuitable for ghcide, so we inlined the implementation locally to fix it. After that, @mpickering yourself propagated the fix upstream, which is the reason it happily does not need to be inlined when building against GHC 8.10 :)

File: src/Development/IDE/GHC/HieAst.hs (hunk 3 above)
Comment (mpickering) [reply src/Development/IDE/GHC/HieAst.hs:102]: The point of copying this file is to remove this part of the implementation if I remember correctly.

File: src/Development/IDE/Core/Rules.hs [hunk 4]
```diff
@@ -1,10 +1,12 @@
 -- Copyright (c) 2019 The DAML Authors. All rights reserved.
 -- SPDX-License-Identifier: Apache-2.0
 
+{-# LANGUAGE CPP #-}
 {-# LANGUAGE TypeFamilies               #-}
 {-# LANGUAGE FlexibleInstances #-}
 {-# LANGUAGE DuplicateRecordFields #-}
 {-# LANGUAGE PatternSynonyms       #-}
+#include "ghc-api-version.h"
```
Comment (mpickering) [inline src/Development/IDE/Core/Rules.hs:9]: Not needed?

File: src/Development/IDE/Core/Rules.hs [hunk 5]
```diff
@@ -1,10 +1,12 @@
 -- Copyright (c) 2019 The DAML Authors. All rights reserved.
 -- SPDX-License-Identifier: Apache-2.0
 
+{-# LANGUAGE CPP #-}
```
Comment (mpickering) [inline src/Development/IDE/Core/Rules.hs:4]: Unused?

Comment (chshersh) [reply src/Development/IDE/Core/Rules.hs]: Removed

File: src/Development/IDE/Core/Rules.hs (hunk 4 above)
Comment (chshersh) [reply src/Development/IDE/Core/Rules.hs]: Yes, not needed. Removed.

**Comment by chshersh** [comment]
Thanks, @pepeiborra for the patch! I guess now the build is failing due to HLint warnings in the new file.

**Comment by chshersh** [comment]
CI for GHC 8.10 fails due to [the test failure](https://dev.azure.com/digitalasset/ghcide/_build/results?buildId=38577&view=logs&j=8c509560-e3d6-573f-8a24-ae9e290d8e4f&t=e939e99c-32dd-58b6-4106-bd1610c76af9&l=2249). The following test fails, don't know how to fix it:

```
  plugins:                                                       FAIL (1.49s)
    test/src/Development/IDE/Test.hs:39:
    Could not find (DsError,(8,14),"Variable not in scope: c") in List [Diagnostic {_range = Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 0}}, _severity = Just DsError, _code = Nothing, _source = Just "typecheck", _message = "/tmp/extra-dir-78866602889079/Testing.hs:1:1: error:\n    Bad interface file: /home/vsts/.stack/snapshots/x86_64-linux/0d09385e35771f64a4c4bf9b92b8b30fbc8ce487126f21b5edfae99a26a1d108/8.10.1/lib/x86_64-linux-ghc-8.10.1/ghc-typelits-knownnat-0.7.2-DCI9V85uoFeJnRWeFtLtpR/GHC/TypeLits/KnownNat.hi\n        Something is amiss; requested module  ghc-typelits-knownnat-0.7.2:GHC.TypeLits.KnownNat differs from name found in the interface file array-0.5.4.0:GHC.TypeLits.KnownNat (if these names look the same, try again with -dppr-debug)", _tags = Nothing, _relatedInformation = Nothing}]
```

File: src-ghc810/Development/IDE/GHC/HieAst.hs [hunk 6]
```diff
@@ -0,0 +1,1929 @@
+
```
[the remark this answers is not in the document]
Comment (chshersh) [reply src-ghc810/Development/IDE/GHC/HieAst.hs:1]: Already done in my last commit: https://github.com/digital-asset/ghcide/pull/519/commits/4d08e4a7bece0b885bb10220a150b83eef00f080

File: src/Development/IDE/GHC/HieAst.hs (hunk 3 above)
Comment (chshersh) [reply src/Development/IDE/GHC/HieAst.hs]: @pepeiborra Thanks for the detailed explanation. This change is reverted. The `HieAst` module for ghc-8.8 has no changes now.

**Comment by pepeiborra** [comment]
> > CI for GHC 8.10 fails due to [the test failure](https://dev.azure.com/digitalasset/ghcide/_build/results?buildId=38577&view=logs&j=8c509560-e3d6-573f-8a24-ae9e290d8e4f&t=e939e99c-32dd-58b6-4106-bd1610c76af9&l=2249). The following test fails, don't know how to fix it:
> > ```
> >   plugins:                                                       FAIL (1.49s)
> >     test/src/Development/IDE/Test.hs:39:
> >     Could not find (DsError,(8,14),"Variable not in scope: c") in List [Diagnostic {_range = Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 0, _character = 0}}, _severity = Just DsError, _code = Nothing, _source = Just "typecheck", _message = "/tmp/extra-dir-78866602889079/Testing.hs:1:1: error:\n    Bad interface file: /home/vsts/.stack/snapshots/x86_64-linux/0d09385e35771f64a4c4bf9b92b8b30fbc8ce487126f21b5edfae99a26a1d108/8.10.1/lib/x86_64-linux-ghc-8.10.1/ghc-typelits-knownnat-0.7.2-DCI9V85uoFeJnRWeFtLtpR/GHC/TypeLits/KnownNat.hi\n        Something is amiss; requested module  ghc-typelits-knownnat-0.7.2:GHC.TypeLits.KnownNat differs from name found in the interface file array-0.5.4.0:GHC.TypeLits.KnownNat (if these names look the same, try again with -dppr-debug)", _tags = Nothing, _relatedInformation = Nothing}]
> > ```
> 
> I can repro this error locally with a ghc 8.10.1 build via Nix, which removes stack from the equation.
> And reproducing what the test does in ghci doesn't show the error, so it's almost certainly not an issue in the related plugin and libraries.

Following GHC's suggestion to use `-dppr-debug`, I can confirm that the two names are really the same. Quite confusing:
```
  /home/pepe/scratch/ghcide/Testing.hs:1:1: error:
  Bad interface file:
  /nix/store/y47mcwxg3xjzm1vncv8vm3km103l1kzn-ghc-typelits-knownnat-0.7.2/lib/ghc-8.10.1/x86_64-linux-ghc-8.10.1/ghc-typelits-knownnat-0.7.2-EOol1HudK6SImK1KLBAdq1/GHC/TypeLits/KnownNat.hi
  Something is amiss; requested module
  ghc-typelits-knownnat-0.7.2-EOol1HudK6SImK1KLBAdq1:GHC.TypeLits.KnownNat differs from name found
  in the interface file ghc-typelits-knownnat-0.7.2-EOol1HudK6SImK1KLBAdq1:GHC.TypeLits.KnownNat (if
  these names look the same, try again with -dppr-debug)
```

**Comment by chshersh** [comment]
@cocreature Thanks for the heads up! I've rebased on the latest `master` and resolved all conflicts.

File: src/Development/IDE/GHC/Orphans.hs [hunk 7]
```diff
@@ -1,8 +1,10 @@
 -- Copyright (c) 2019 The DAML Authors. All rights reserved.
 -- SPDX-License-Identifier: Apache-2.0
 
+{-# LANGUAGE CPP               #-}
```
Comment (cocreature) [inline src/Development/IDE/GHC/Orphans.hs:4]: Hlint is failing because we explicitly whitelist modules that are allowed to use CPP. You can just add this module to the list: https://github.com/digital-asset/ghcide/blob/9adb11125ed8c671e802405a272c5c34ec1df0d3/.hlint.yaml#L77

Comment (chshersh) [reply src/Development/IDE/GHC/Orphans.hs:4]: Thanks! Should be fixed now.

**Comment by cocreature** [comment]
Hm, the test failure still persists. I have to admit that I have no idea what is going wrong here :thinking:

**Comment by pepeiborra** [comment]
Only the Linux build of 8.10 fails. The windows build succeeds. Platform specific GHC bug?

**Comment by cocreature** [comment]
We don’t actually run tests on Windows at all atm. We just check that they compile.

In the interest in moving this forward, how about we open an issue for the failing test and just disable it for 8.10 for now? This still seems like a clear improvement over the status quo so it would be a shame to block it on this.

File: stack810.yaml [hunk 8]
```diff
@@ -0,0 +1,17 @@
+resolver: nightly-2020-02-13
+compiler: ghc-8.10.1
+allow-newer: true
+packages:
+- .
+extra-deps:
+- haskell-lsp-0.21.0.0
+- haskell-lsp-types-0.21.0.0
+- lsp-test-0.10.2.0
+- ghc-check-0.1.0.3
```
Comment (pepeiborra) [inline stack810.yaml:10]:
```suggestion
- ghc-check-0.3.0.1
```

**Comment by chshersh** [comment]
@pepeiborra Thanks for the fix! The build seems passing now 👍 
@cocreature @mpickering Is there something left to do in this PR?
