### ISSUE TITLE
Build with GHC 8.10

### ISSUE THREAD

**Issue by chshersh** [digital-asset/ghcide#518]
I'm trying to build `ghcide` using recently released GHC 8.10. After updating dependencies correspondingly, I see the following error message:

```
src/Development/IDE/GHC/HieAst.hs:30:1: error:
    Could not find module ‘HsSyn’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
30 | import HsSyn
   | ^^^^^^^^^^^^

src/Development/IDE/GHC/HieAst.hs:37:37: error:
    Module ‘Type’ does not export ‘mkFunTys’
   |
37 | import Type                       ( mkFunTys, Type )
   |                                     ^^^^^^^^
```

I can see that at least the `HsSyn` module is not present in `ghc-lib-parser-8.10.1.20200324`.

cc @pepeiborra

**Comment by pepeiborra** [comment]
This is blocking us from upgrading to ghc 8.10

**Comment by ndmitchell** [comment]
The diff for HLint might be instructive - https://github.com/ndmitchell/hlint/pull/934 suggests the kind of changes that will be required.
